version: "3.8"

services:
  api:
    container_name: avatar-resizer_api
    build:
      context: ./
      dockerfile: ./.docker/api/Dockerfile
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./api:/var/www/app
    command:
      sh -c 'yarn install && yarn dev'
    networks:
      - resizer

  redis-server: 
    image: redis:6.2
    container_name: avatar-resizer_redis
    networks:
      - resizer
  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: beautiful-rabbit
    ports: 
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.docker/rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./.docker/rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./.docker/rabbitmq/logs:/var/log/rabbitmq/log
    networks:
      - resizer

  db:
    image: postgres:13.3
    container_name: avatar-resizer_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - resizer

  adminer:
    image: adminer:4.8.1
    container_name: avatar-resizer_adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - resizer

volumes:
  db:

networks:
  resizer: